package ru.gustavo.astonhomework3

object Repo {
    val countries = listOf(
        Country(
            1,
            R.drawable.australia,
            "Australia"
        ),
        Country(
            2,
            R.drawable.brasil,
            "Brazil"
        ),
        Country(
            3,
            R.drawable.canada,
            "Canada"
        ),
        Country(
            4,
            R.drawable.chile,
            "Chile"
        ),
        Country(
            5,
            R.drawable.china,
            "China"
        ),
        Country(
            6,
            R.drawable.colombia,
            "Colombia"
        ),
        Country(
            7,
            R.drawable.denmark,
            "Denmark"
        ),
        Country(
            8,
            R.drawable.egypt,
            "Egypt"
        ),
        Country(
            9,
            R.drawable.finland,
            "Finland"
        ),
        Country(
            10,
            R.drawable.france,
            "France"
        ),
        Country(
            11,
            R.drawable.germany,
            "Germany"
        ),
        Country(
            12,
            R.drawable.greece,
            "Greece"
        ),
        Country(
            13,
            R.drawable.guatemala,
            "Guatemala"
        ),
        Country(
            14,
            R.drawable.ireland,
            "Ireland"
        ),
        Country(
            15,
            R.drawable.island,
            "Island"
        ),
        Country(
            16,
            R.drawable.italia,
            "Italia"
        ),
        Country(
            17,
            R.drawable.japan,
            "Japan"
        ),
        Country(
            18,
            R.drawable.libya,
            "Libya"
        ),
        Country(
            19,
            R.drawable.mexico,
            "Mexico"
        ),
        Country(
            20,
            R.drawable.netherlands,
            "Netherlands"
        ),
        Country(
            21,
            R.drawable.new_zealand,
            "New Zealand"
        ),
        Country(
            22,
            R.drawable.norway,
            "Norway"
        ),
        Country(
            23,
            R.drawable.poland,
            "Poland"
        ),
        Country(
            24,
            R.drawable.russia,
            "Russia"
        ),
        Country(
            25,
            R.drawable.spain,
            "Spain"
        ),
        Country(
            26,
            R.drawable.sweden,
            "Sweden"
        ),
        Country(
            27,
            R.drawable.uk,
            "United Kingdom"
        ),
        Country(
            28,
            R.drawable.usa,
            "United States"
        ),
        Country(
            29,
            R.drawable.venezuela,
            "Venezuela"
        ),
        Country(
            30,
            R.drawable.zambia,
            "Zambia"
        )
    )
}